"""Create batch table

Revision ID: 652a15bbc149
Revises:
Create Date: 2026-07-28 16:56:05.540259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "652a15bbc149"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("batch_name", sa.String(length=100), nullable=False),
        sa.Column("crop_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "FAILED", "ARCHIVED", name="batchstatus"),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("expected_harvest_date", sa.DateTime(), nullable=False),
        sa.Column("actual_harvest_date", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=150), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_batches_batch_name"), "batches", ["batch_name"], unique=True
    )
    op.create_index(op.f("ix_batches_id"), "batches", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_batches_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_name"), table_name="batches")
    op.drop_table("batches")
    # ### end Alembic commands ###
