"""update daily_logs schema to match ticket 6

Revision ID: d22ad1b0cfae
Revises: 9cd6dacab322
Create Date: 2026-08-01 19:15:56.493662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd22ad1b0cfae'
down_revision: Union[str, Sequence[str], None] = '9cd6dacab322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('ph_level', sa.Float(), nullable=True))
    op.add_column('daily_logs', sa.Column('moisture', sa.Float(), nullable=True))
    op.add_column('daily_logs', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('daily_logs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('daily_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('daily_logs', 'log_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_daily_logs_log_date'), 'daily_logs', ['log_date'], unique=False)
    op.drop_column('daily_logs', 'co2_ppm')
    op.drop_column('daily_logs', 'observations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_logs', sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('daily_logs', sa.Column('co2_ppm', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_daily_logs_log_date'), table_name='daily_logs')
    op.alter_column('daily_logs', 'log_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('daily_logs', 'updated_at')
    op.drop_column('daily_logs', 'created_at')
    op.drop_column('daily_logs', 'notes')
    op.drop_column('daily_logs', 'moisture')
    op.drop_column('daily_logs', 'ph_level')
    # ### end Alembic commands ###
