"""initial_schema_with_trackings

Revision ID: dbfcbe19707e
Revises:
Create Date: 2026-08-05 17:59:03.229734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dbfcbe19707e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("batch_name", sa.String(length=100), nullable=False),
        sa.Column("crop_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "FAILED", "ARCHIVED", name="batchstatus"),
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("expected_harvest_date", sa.DateTime(), nullable=False),
        sa.Column("actual_harvest_date", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=150), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_batches_batch_name"), "batches", ["batch_name"], unique=True
    )
    op.create_index(op.f("ix_batches_id"), "batches", ["id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(op.f("ix_alerts_batch_id"), "alerts", ["batch_id"], unique=False)
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_table(
        "trackings",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("tracking_date", sa.Date(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Float(), nullable=True),
        sa.Column("ph_level", sa.Float(), nullable=True),
        sa.Column("moisture", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "humidity >= 0 AND humidity <= 100", name="check_humidity_range"
        ),
        sa.CheckConstraint(
            "moisture >= 0 AND moisture <= 100", name="check_moisture_range"
        ),
        sa.CheckConstraint("ph_level >= 0 AND ph_level <= 14", name="check_ph_range"),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trackings_batch_id"), "trackings", ["batch_id"], unique=False
    )
    op.create_index(op.f("ix_trackings_id"), "trackings", ["id"], unique=False)
    op.create_index(
        op.f("ix_trackings_tracking_date"), "trackings", ["tracking_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trackings_tracking_date"), table_name="trackings")
    op.drop_index(op.f("ix_trackings_id"), table_name="trackings")
    op.drop_index(op.f("ix_trackings_batch_id"), table_name="trackings")
    op.drop_table("trackings")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_batch_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_batches_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_name"), table_name="batches")
    op.drop_table("batches")
    # ### end Alembic commands ###
